[package]
name = "jsonrpc-client-http"
version = "0.1.0"
authors = ["Linus Färnstrand <linus@mullvad.net>"]

[dependencies]
error-chain = "0.10"
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1"
jsonrpc-client-core = { path = "../core" }
tokio-core = "0.1"
